Basic engine work: implement #19
tccppgg/rect pull request #21
Opened 2020-10-06 13:45 UTC by NotAPenguin0

This implements #19 into the project.

2020-10-06 13:58 UTC, alexdevteam requested changes

2020-10-06 13:58 UTC, alexdevteam commented on src/engine/private/yml_importer.cpp
> +			}
We also need `- import: path` functionality, should also accept relative paths

2020-10-07 19:28 UTC, NotAPenguin0 commented on src/engine/private/yml_importer.cpp
> +			}
Added in 52d8500

2020-10-07 20:32 UTC, alexdevteam approved these changes
this will not check for recursive imports, but eh, it's ok

2020-10-07 20:36 UTC, NotAPenguin0 commented
Recursive imports as in file A importing B and B importing A? That should probably hard error/crash anyway so I don't think it's a big deal.

2020-10-08 08:10 UTC, merged